// src/app/home-page.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { IHomePage } from './shared/contentful';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-home-page',
  imports: [MatButtonModule],
  template: `
    <section class="hero">
      <img [src]="home().heroImage" alt="hero_image" />

      <h1 class="mat-title-large">{{ home().heroTitle }}</h1>

      <p>{{ home().heroDescription }}</p>

      <button mat-flat-button>{{ home().linkText }}</button>
    </section>
  `,
  styles: [
    `
      @use '@angular/material' as mat;
      @use 'theme' as theme;

      .hero {
        position: relative;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        justify-content: center;

        > button {
          @include mat.button-overrides(
            (
              filled-container-color:
                mat.get-theme-color(theme.$theme, secondary-container),
              filled-label-text-color:
                mat.get-theme-color(theme.$theme, on-secondary-container),
            )
          );
        }

        padding: 1rem;
        @media (min-width: 599px) {
          padding: 2rem;
        }

        color: mat.get-theme-color(theme.$theme, on-primary);

        height: 40dvh;
        @media (min-width: 599px) {
          height: 50dvh;
        }

        img {
          position: absolute;
          inset: 0;
          height: 100%;
          width: 100%;
          object-fit: cover;
          z-index: -1;
        }

        &::after {
          content: '';
          z-index: -1;
          position: absolute;
          inset: 0;
          background: rgba(mat.get-theme-color(theme.$theme, primary), 0.5);
        }
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HomePageComponent {
  readonly home = input.required<IHomePage>();
}

// src/lib/pages/home-page.svelte
<script lang="ts">

    import {Button} from "$lib/components/ui/button/index.js";
    import type {IHomePage} from "$lib/sanity.model";

    let {home, locale}: { home: IHomePage, locale: string } = $props();

    const heroImageUrl = $derived(() => home.page.heroImage.asset!.url)

    const heroLink = $derived(() => home.page.linkTo!.slug)
</script>
<section
        class="flex flex-col items-start justify-center relative h-[40dvh] md:h-[50dvh] after:absolute after:inset-0 after:block after:bg-primary after:opacity-50 after:z-[-1] text-primary-foreground">
    <img aria-hidden="true" alt="Hero" class="z-[-1] absolute inset-0 h-full w-full object-cover"
         src={heroImageUrl()}/>
    <div class="mx-auto w-full md:max-w-[70vw] px-8">
        <h1 class="heading-1">{home.page.heroTitle}</h1>
        <p class="mt-4">{home.page.heroDescription}</p>

        <a href={`/${locale}/${heroLink()}`}>
            <Button class="mt-8" variant="secondary">
                {home.page.linkText}
            </Button>
        </a>
    </div>
</section>
